### ISSUE TITLE
SSR for next.js

### ISSUE THREAD

**Issue by FlyOrDie** [iiroj/styled-modal#9]
Good day!

Following the steps to make it work with SSR using next.js, but getting an error **'document is not defined'** somewhere here: _/styled-modal/dist/index.cjs.js:1:4798_

```
const sheet = new ServerStyleSheet();
    const originalRenderPage = ctx.renderPage;
    const collectedPortals: React.ReactNode[] = [];

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: App => props => sheet.collectStyles(
            <PortalCollector portals={collectedPortals}>
              <App {...props} />
            </PortalCollector>
            )
        });

      const initialProps = await Document.getInitialProps(ctx);

      return {
        ...initialProps,
        styles: [
          <React.Fragment key={'withStyledComponents'}>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </React.Fragment>
        ]
      };
    } finally {
      sheet.seal();
    }
  }
```

And I am executing flushPortals just before Definition of my class in _app.tsx file. Any ideas? Thank you :)

**Comment by iiroj** [comment]
Hello, sorry about the lack of response! Apparently I haven't been receiving any notifications from GitHub.

**Comment by iiroj** [comment]
There's a `document` reference in in a `useRef` hook, that's probably messing it up. Let me fix...

**Comment by iiroj** [comment]
I released a new version where this is hopefully fixed, can you re-test?

**Comment by FlyOrDie** [comment]
Sorry, also had an issue with notifications :D For that moment I had to give away the idea of modal, but I'll let you know as soon as it'll be tested. Thank you very much :)
